export interface LiveConcert {
  venue: string
  city: string
  country: string
  date: string
  time: string
  status: string
  genre: string
  capacity: string
  price: string
  locationUrl: string
}

const MANUAL_LIVE_CONCERTS: LiveConcert[] = [
  // UPCOMING
  {
    venue: "Mauerpark",
    city: "",
    country: "",
    date: "2026-12-01",
    time: "",
    status: "Upcoming",
    genre: "World Music",
    capacity: "",
    price: "",
    locationUrl: "",
  },
  {
    venue: "Zuckerzauber",
    city: "",
    country: "",
    date: "2026-12-02",
    time: "",
    status: "Upcoming",
    genre: "World Music",
    capacity: "",
    price: "",
    locationUrl: "",
  },

  // HISTORY
  {
    venue: "Werk 9",
    city: "",
    country: "",
    date: "2025-01-01",
    time: "",
    status: "Completed",
    genre: "World Music",
    capacity: "",
    price: "",
    locationUrl: "",
  },
  {
    venue: "ART Stalker",
    city: "",
    country: "",
    date: "2025-01-02",
    time: "",
    status: "Completed",
    genre: "World Music",
    capacity: "",
    price: "",
    locationUrl: "",
  },
  {
    venue: "Horns Erben",
    city: "",
    country: "",
    date: "2025-01-03",
    time: "",
    status: "Completed",
    genre: "World Music",
    capacity: "",
    price: "",
    locationUrl: "",
  },
  {
    venue: "KAOS",
    city: "",
    country: "",
    date: "2025-01-04",
    time: "",
    status: "Completed",
    genre: "World Music",
    capacity: "",
    price: "",
    locationUrl: "",
  },
  {
    venue: "Zuckerzauber",
    city: "",
    country: "",
    date: "2025-01-05",
    time: "",
    status: "Completed",
    genre: "World Music",
    capacity: "",
    price: "",
    locationUrl: "",
  },
  {
    venue: "Kulturelle Landapie",
    city: "",
    country: "",
    date: "2025-01-06",
    time: "",
    status: "Completed",
    genre: "World Music",
    capacity: "",
    price: "",
    locationUrl: "",
  },
  {
    venue: "Sommersonnenwende Festival",
    city: "",
    country: "",
    date: "2025-01-07",
    time: "",
    status: "Completed",
    genre: "World Music",
    capacity: "",
    price: "",
    locationUrl: "",
  },
  {
    venue: "Mauerpark",
    city: "",
    country: "",
    date: "2025-01-08",
    time: "",
    status: "Completed",
    genre: "World Music",
    capacity: "",
    price: "",
    locationUrl: "",
  },
  {
    venue: "Privatclub",
    city: "",
    country: "",
    date: "2025-01-09",
    time: "",
    status: "Completed",
    genre: "World Music",
    capacity: "",
    price: "",
    locationUrl: "",
  },
  {
    venue: "Uebel & Gefährlich",
    city: "",
    country: "",
    date: "2025-01-10",
    time: "",
    status: "Completed",
    genre: "World Music",
    capacity: "",
    price: "",
    locationUrl: "",
  },
  {
    venue: "Schnabeltierfestival",
    city: "",
    country: "",
    date: "2025-01-11",
    time: "",
    status: "Completed",
    genre: "World Music",
    capacity: "",
    price: "",
    locationUrl: "",
  },
  {
    venue: "Waltweiser Festival",
    city: "",
    country: "",
    date: "2025-01-12",
    time: "",
    status: "Completed",
    genre: "World Music",
    capacity: "",
    price: "",
    locationUrl: "",
  },
]

export async function loadLiveConcerts(): Promise<LiveConcert[]> {
  return [...MANUAL_LIVE_CONCERTS]
}